
project_id = "zeiodratpawnnbgnflvi"

[api]
# Port to run the API on
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = false

[studio]
enabled = false

[inbucket]
enabled = false

[auth]
enabled = true

[storage]
enabled = false

[functions]
func_timeout_seconds = 60
enabled = true

