
project_id = "zeiodratpawnnbgnflvi"

[functions]
[functions.nuvemshop-auth]
verify_jwt = false
[functions.nuvemshop-products]
verify_jwt = false
[functions.sync-product-analytics]
verify_jwt = true
[functions.nimbus-auth]
verify_jwt = false
