
import { EditorState } from '../types';
import { Block } from '@/types/editor';
import { generateBlockHtml } from '@/utils/htmlGenerators';

/**
 * Generates the complete HTML output for the product description
 * with exact same styling that will be exported to Nuvemshop
 */
export const generateCompleteHtml = (state: EditorState): string => {
  // Check if description exists and has blocks
  if (!state.description || !state.description.blocks || state.description.blocks.length === 0) {
    return '<div>Nenhum conteúdo adicionado</div>';
  }

  // Filter only visible blocks
  const visibleBlocks = state.description.blocks.filter(block => {
    return block && typeof block === 'object' && 'visible' in block && block.visible;
  });

  if (visibleBlocks.length === 0) {
    return '<div>Nenhum bloco visível</div>';
  }
  
  // Generate HTML for each block with standard styling
  let blocksHtml = '';
  
  for (let i = 0; i < visibleBlocks.length; i++) {
    const block = visibleBlocks[i];
    try {
      // Generate block HTML with all inline styles
      const blockHtml = generateBlockHtml(block);
      
      // Determine spacing based on block style
      let marginBottom = '1.5rem';
      if (block.style?.blockSpacing === 'none') {
        marginBottom = '0';
      } else if (block.style?.blockSpacing === 'xs' || block.style?.blockSpacing === 'small') {
        marginBottom = '0.75rem';
      } else if (block.style?.blockSpacing === 'md' || block.style?.blockSpacing === 'large') {
        marginBottom = '2.25rem';
      } else if (block.style?.blockSpacing === 'lg' || block.style?.blockSpacing === 'xl' || block.style?.blockSpacing === 'extra-large') {
        marginBottom = '3rem';
      }
      
      // Apply spacing only if not the last block
      const marginClass = i < visibleBlocks.length - 1 ? `margin-bottom: ${marginBottom};` : '';
      
      // Add block HTML with metadata in attributes for later parsing
      blocksHtml += `<div 
        style="${marginClass}" 
        id="product-block-${block.id}" 
        data-block-type="${block.type}" 
        data-block-columns="${block.columns}"
      >\n`;
      blocksHtml += blockHtml + '\n';
      blocksHtml += '</div>\n';
    } catch (error) {
      console.error(`Error generating HTML for block ${block.id}:`, error);
      blocksHtml += `<div style="padding: 0.5rem; color: #f00; border: 1px solid #f00;">\n`;
      blocksHtml += `Erro ao gerar HTML para o bloco ${block.id}\n`;
      blocksHtml += '</div>\n';
    }
  }

  console.log("HTML output gerado com " + visibleBlocks.length + " blocos visíveis");
  
  // Add CSS reset and responsive styles to ensure consistent rendering
  const cssReset = `
    <style>
      .nuvemshop-product-description * {
        box-sizing: border-box;
      }
      .nuvemshop-product-description img {
        max-width: 100%;
        height: auto;
      }
      @media (max-width: 768px) {
        .nuvemshop-product-description [class*="-container"] > [class*="-item"] {
          width: 100% !important;
          margin-left: 0 !important;
          margin-right: 0 !important;
        }
      }
    </style>
  `;
  
  // Add a comment at the beginning to identify this as a description generated by our editor
  const generatedComment = `<!-- Descrição gerada pelo Editor de Descrições - Editado em: ${new Date().toISOString()} -->`;
  
  // Add a wrapper for the description that uses standard styling
  return `${generatedComment}\n<div class="nuvemshop-product-description">${cssReset}${blocksHtml}</div>`;
}
